# fly.toml app configuration file generated for pogbot-d on 2023-09-19T13:08:11-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pogbot-dev"
primary_region = "scl"

[build]

[http_service]
  internal_port = 7171
  force_https = true
  min_machines_running = 0
  processes = ["app"]

[metrics]
  path = "/metrics"